# DATASET OPTIONS
OBS_LEN = 8
PRED_LEN = 12
TRAIN_DATASET_PATH = 'C:/Users/visha/MasterThesis/Argoverse Sub Sample/train111'
VAL_DATASET_PATH = 'C:/Users/visha/MasterThesis/Argoverse Sub Sample/val111'
TEST_DATASET_PATH = 'C:/Users/visha/MasterThesis/Argoverse Sub Sample/test'
CHECKPOINT_NAME = 'Checkpoints/1epochWithSigmoid.pt'

# NUMBER OF CONDITION FLAG - activate one of the following flags
SINGLE_CONDITIONAL_MODEL = False
MULTI_CONDITIONAL_MODEL = True

# DATASET FLAGS FOR ANALYZING THE MAX SPEEDS.
AV_MAX_SPEED = 2.0
OTHER_MAX_SPEED = 3.8
AGENT_MAX_SPEED = 3.2

# PYTORCH DATA LOADER OPTIONS
NUM_WORKERS = 4
BATCH = 32
BATCH_NORM = False
ACTIVATION_RELU = 'relu'
ACTIVATION_LEAKYRELU = 'leakyrelu'

# Time between consecutive frames
FRAMES_PER_SECOND_SINGLE_CONDITION = 0.4
FRAMES_PER_SECOND_MULTI_CONDITION = 0.1
NORMALIZATION_FACTOR = 10


# ENCODER DECODER HIDDEN DIMENSION OPTIONS
H_DIM_GENERATOR_MULTI_CONDITION = 32
H_DIM_DISCRIMINATOR_MULTI_CONDITION = 64

H_DIM_GENERATOR_SINGLE_CONDITION = 16
H_DIM_DISCRIMINATOR_SINGLE_CONDITION = 32

MLP_INPUT_DIM_MULTI_CONDITION = 4
MLP_INPUT_DIM_SINGLE_CONDITION = 3

# HYPER PARAMETERS OPTIONS
G_LEARNING_RATE, D_LEARNING_RATE = 1e-3, 1e-3
NUM_LAYERS = 1
DROPOUT = 0
NUM_EPOCHS = 1
CHECKPOINT_EVERY = 100
MLP_DIM = 64
EMBEDDING_DIM = 16
BOTTLENECK_DIM = 32
NOISE_DIM = (8, )
DECODER_TIMESTEP_POOLING = False

L2_LOSS_WEIGHT = 1
SPEED_TO_ADD = 0

NUM_ITERATIONS = 3200
POOLING_TYPE = True
USE_GPU = 0

# SPEED CONTROL FLAGS
TEST_METRIC = 1  # 0 for ground_truth speed. To simulate trajectories, change the flag to 1. This flag is used during testing and inference phase.
TRAIN_METRIC = 0  # Used for training the model with the ground truth
VERIFY_OUTPUT_SPEED = 1

# ADD_SPEED_EVERY_FRAME, STOP_PED, CONSTANT_SPEED_FOR_ALL_PED, ADD_SPEED_PARTICULAR_FRAME - Only one flag out of the 4 can be activated at once.

DIFFERENT_SPEED_FOR_ALL = True
AV_SPEED = 0.2
AGENT_SPEED = 0.4
OTHER_SPEED = 0.5

CONSTANT_SPEED_FOR_ALL_PED = False  # CONSTANT_SPEED flag will be active only if CONSTANT_SPEED_FOR_ALL_PED is True
CONSTANT_SPEED = 0.2

ANIMATED_VISUALIZATION_CHECK = 1

G_STEPS = 1
D_STEPS = 2
BEST_K = 10
PRINT_EVERY = 100
NUM_SAMPLES = 20
NOISE = True
NUM_SAMPLE_CHECK = 5000